spring.application.name=FirstJobApp
spring.profiles.active=local
server.port=8081

# Disable devtools restart (prevents timezone + datasource weird issues)
spring.devtools.restart.enabled=false

# ===============================
# PostgreSQL DataSource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/JobApp
spring.datasource.username=p_yeole
spring.datasource.password=test123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# DO NOT specify dialect (Spring Boot auto detects)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Logging
# ===============================
logging.level.org.springdoc=DEBUG
logging.level.org.postgresql=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# Security / Misc
# ===============================
spring.main.allow-bean-definition-overriding=true

# ===============================
# JWT
# ===============================
jwt.secret=MySuperStrongSecretKeyForJWT1234567890
jwt.expiration=3600000